# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 09:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('status', models.IntegerField(choices=[(0, 'Unapproved'), (1, 'Approved'), (2, 'Paused'), (3, 'Running'), (4, 'Expired')], default=0)),
                ('location', models.IntegerField(choices=[(0, 'Karachi'), (1, 'Rawalpindi'), (2, 'Islamabad'), (3, 'Lahore'), (4, 'Quetta'), (5, 'Hyderabad'), (6, 'Multan'), (7, 'Sukkur'), (8, 'Gujrat'), (9, 'Peshawer'), (10, 'Sialkot'), (11, 'Faisalabad'), (12, 'Gujranwala'), (13, 'Wah'), (14, 'Sarghoda'), (15, 'Bahwalpur'), (16, 'Mardan'), (17, 'Abbottabad'), (18, 'Swat'), (19, 'Gilgit'), (20, 'Skardu')], default=0)),
                ('address', models.TextField()),
                ('link_url', models.TextField()),
                ('link_descriptor', models.TextField(default='click here!')),
                ('contact_preference', models.IntegerField(choices=[(0, 'Call/Text'), (1, 'Call'), (2, 'Text')], default=0)),
                ('submitted_time', models.DateTimeField(auto_now_add=True)),
                ('total_money_paid', models.IntegerField(default=0)),
                ('last_money_topup', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LocationCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField(choices=[(0, 'Karachi'), (1, 'Rawalpindi'), (2, 'Islamabad'), (3, 'Lahore'), (4, 'Quetta'), (5, 'Hyderabad'), (6, 'Multan'), (7, 'Sukkur'), (8, 'Gujrat'), (9, 'Peshawer'), (10, 'Sialkot'), (11, 'Faisalabad'), (12, 'Gujranwala'), (13, 'Wah'), (14, 'Sarghoda'), (15, 'Bahwalpur'), (16, 'Mardan'), (17, 'Abbottabad'), (18, 'Swat'), (19, 'Gilgit'), (20, 'Skardu')], default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ad')),
            ],
        ),
        migrations.CreateModel(
            name='Topup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('money_paid', models.IntegerField()),
                ('is_running', models.BooleanField(default=True)),
                ('expiry_time', models.DateTimeField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ad')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='locationcounter',
            unique_together=set([('ad', 'location')]),
        ),
    ]
