# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 07:36
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(blank=True, null=True)),
                ('link_url', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('button_label', models.TextField(default='Yeh Dubao!')),
                ('contact_preference', models.IntegerField(choices=[(0, 'Call/Text'), (1, 'Call'), (2, 'Text')], default=0)),
                ('only_ladies', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Unapproved'), (1, 'Approved/Unpaid'), (2, 'Paused'), (3, 'Claimed'), (3, 'Running'), (4, 'Stopped'), (5, 'Expired')], default=0)),
                ('submitted_time', models.DateTimeField(auto_now_add=True)),
                ('total_money_paid', models.IntegerField(default=0)),
                ('last_money_topup', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LocationCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField(choices=[(0, 'Karachi'), (1, 'Rawalpindi'), (2, 'Islamabad'), (3, 'Lahore'), (4, 'Quetta'), (5, 'Hyderabad'), (6, 'Multan'), (7, 'Sukkur'), (8, 'Gujrat'), (9, 'Peshawer'), (10, 'Sialkot'), (11, 'Faisalabad'), (12, 'Gujranwala'), (13, 'Wah'), (14, 'Sarghoda'), (15, 'Bahwalpur'), (16, 'Mardan'), (17, 'Abbottabad'), (18, 'Swat'), (19, 'Gilgit'), (20, 'Skardu')], default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ad')),
            ],
        ),
        migrations.CreateModel(
            name='SalesAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.FloatField(default=0.0)),
                ('rating_count', models.IntegerField(default=0)),
                ('total_claimed', models.IntegerField(default=0)),
                ('total_closed', models.IntegerField(default=0)),
                ('money_made', models.IntegerField(default=0)),
                ('commission_owed', models.IntegerField(default=0)),
                ('commission_paid', models.IntegerField(default=0)),
                ('last_closing_time', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paisa_type', models.IntegerField(choices=[(0, 'easyPaisa'), (1, 'timePey'), (2, 'uPay'), (3, 'jazzCash'), (4, 'mobilePaisa')], default=0)),
                ('paisa_id', models.IntegerField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('money_paid', models.IntegerField()),
                ('is_running', models.BooleanField(default=True)),
                ('expiry_time', models.DateTimeField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ad')),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SalesAgent')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='claimed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SalesAgent'),
        ),
        migrations.AlterUniqueTogether(
            name='locationcounter',
            unique_together=set([('ad', 'location')]),
        ),
    ]
