# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsoutgoing',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Ad'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unapproved'), (1, 'Approved/Unpaid'), (2, 'Paused'), (3, 'Claimed'), (4, 'Closed'), (5, 'Running'), (6, 'Suspended'), (7, 'Stopped'), (8, 'Expired')], default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING PAYMENT'), (1, 'PENDING KHOOFIA CODE'), (2, 'PAYMENT unverified'), (3, 'PAYMENT VERIFIED'), (4, 'PAYMENT IS LESS'), (5, 'Mismatched payment')], default=0),
        ),
    ]
