# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 10:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topup',
            name='is_running',
        ),
        migrations.AddField(
            model_name='salesagent',
            name='location',
            field=models.IntegerField(choices=[(0, 'Karachi'), (1, 'Rawalpindi'), (2, 'Islamabad'), (3, 'Lahore'), (4, 'Quetta'), (5, 'Hyderabad'), (6, 'Multan'), (7, 'Sukkur'), (8, 'Gujrat'), (9, 'Peshawer'), (10, 'Sialkot'), (11, 'Faisalabad'), (12, 'Gujranwala'), (13, 'Wah'), (14, 'Sarghoda'), (15, 'Bahwalpur'), (16, 'Mardan'), (17, 'Abbottabad'), (18, 'Swat'), (19, 'Gilgit'), (20, 'Skardu')], default=0),
        ),
        migrations.AddField(
            model_name='salesagent',
            name='phone_number',
            field=models.CharField(default=1, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topup',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topup',
            name='status',
            field=models.IntegerField(choices=[(0, 'closed'), (1, 'paid'), (2, 'expired')], default=0),
        ),
    ]
