# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING PAYMENT'), (1, 'PENDING KHOOFIA CODE'), (2, 'PAYMENT unverified'), (3, 'PAYMENT VERIFIED'), (4, 'PAYMENT IS LESS'), (5, 'Mismatched payment'), (6, 'PAYMENT IS MORE')], default=0),
        ),
    ]
