# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_ad_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='link_descriptor',
        ),
        migrations.AddField(
            model_name='ad',
            name='button_label',
            field=models.TextField(default='Yeh Dubao!'),
        ),
        migrations.AddField(
            model_name='ad',
            name='image_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unapproved'), (1, 'Approved/Unpaid'), (2, 'Paused'), (3, 'Running'), (4, 'Stopped'), (5, 'Expired')], default=0),
        ),
    ]
