# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161206_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField(choices=[(0, 'Karachi'), (1, 'Rawalpindi'), (2, 'Islamabad'), (3, 'Lahore'), (4, 'Quetta'), (5, 'Hyderabad'), (6, 'Multan'), (7, 'Sukkur'), (8, 'Gujrat'), (9, 'Peshawer'), (10, 'Sialkot'), (11, 'Faisalabad'), (12, 'Gujranwala'), (13, 'Wah'), (14, 'Sarghoda'), (15, 'Bahwalpur'), (16, 'Mardan'), (17, 'Abbottabad'), (18, 'Swat'), (19, 'Gilgit'), (20, 'Skardu')])),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ad')),
            ],
        ),
        migrations.CreateModel(
            name='TopupLocationCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField(choices=[(0, 'Karachi'), (1, 'Rawalpindi'), (2, 'Islamabad'), (3, 'Lahore'), (4, 'Quetta'), (5, 'Hyderabad'), (6, 'Multan'), (7, 'Sukkur'), (8, 'Gujrat'), (9, 'Peshawer'), (10, 'Sialkot'), (11, 'Faisalabad'), (12, 'Gujranwala'), (13, 'Wah'), (14, 'Sarghoda'), (15, 'Bahwalpur'), (16, 'Mardan'), (17, 'Abbottabad'), (18, 'Swat'), (19, 'Gilgit'), (20, 'Skardu')], default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('topup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Topup')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='locationcounter',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='locationcounter',
            name='ad',
        ),
        migrations.DeleteModel(
            name='LocationCounter',
        ),
        migrations.AlterUniqueTogether(
            name='topuplocationcounter',
            unique_together=set([('topup', 'location')]),
        ),
        migrations.AlterUniqueTogether(
            name='locations',
            unique_together=set([('ad', 'location')]),
        ),
    ]
