# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161130_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='only_ladies',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='link_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
