# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161207_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_damadam',
            field=models.BooleanField(default=True),
        ),
    ]
