# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161201_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.FloatField(default=0.0)),
                ('rating_count', models.IntegerField(default=0)),
                ('total_claimed', models.IntegerField(default=0)),
                ('total_closed', models.IntegerField(default=0)),
                ('money_made', models.IntegerField(default=0)),
                ('commission_owed', models.IntegerField(default=0)),
                ('commission_paid', models.IntegerField(default=0)),
                ('last_closing_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='topup',
            name='paisa_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='topup',
            name='paisa_type',
            field=models.IntegerField(choices=[(0, 'easyPaisa'), (1, 'timePey'), (2, 'uPay'), (3, 'jazzCash'), (4, 'mobilePaisa')], default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unapproved'), (1, 'Approved/Unpaid'), (2, 'Paused'), (3, 'Claimed'), (3, 'Running'), (4, 'Stopped'), (5, 'Expired')], default=0),
        ),
        migrations.AddField(
            model_name='ad',
            name='claimed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SalesAgent'),
        ),
        migrations.AddField(
            model_name='topup',
            name='closed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SalesAgent'),
        ),
    ]
