# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ad_is_damadam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='is_damadam',
        ),
        migrations.AddField(
            model_name='ad',
            name='app_code',
            field=models.IntegerField(default=0),
        ),
    ]
