# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161207_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
