# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ad_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSIncoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(blank=True, max_length=20, null=True)),
                ('sender', models.CharField(max_length=20)),
                ('sent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('time_recieved', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.CharField(blank=True, max_length=918, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMSOutgoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciever', models.CharField(max_length=20)),
                ('message', models.CharField(blank=True, max_length=918, null=True)),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'sent')], default=0)),
                ('sent_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
