# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_smsincoming_smsoutgoing'),
    ]

    operations = [
        migrations.AddField(
            model_name='topuplocationcounter',
            name='impressions',
            field=models.IntegerField(default=0),
        ),
    ]
