# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_topuplocationcounter_impressions'),
    ]

    operations = [
        migrations.AddField(
            model_name='topup',
            name='total_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topup',
            name='total_impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topup',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topup',
            name='status',
            field=models.IntegerField(choices=[(0, 'closed'), (1, 'paid'), (2, 'free'), (3, 'expired')], default=0),
        ),
    ]
